### ISSUE TITLE
Link and multi links field types do not add " " around each link in frontmatter

### ISSUE THREAD

**Issue by TheNewParad1gm** [mdelobelle/metadatamenu#103]
Link and Multiple links options do not add " " around the link in frontmatter.

This means that when you create a dataview table of these values they do not actually appear as links in the table, but show instead as plain text.

It would also be really useful to be able to add a "new" link that doesn't currently exist as a note yet (but gives you the option to create it when you hover... like regular internal links).

**Comment by gui-costa** [comment]
I love your work! It's a step up to add structure to our Obsidian workflow!
Hope this issue is solved! (btw, why do you see it as enhancement? Currently, when you add wikilinks to frontmatter, they do not work as wikilinks. When you add quotes, it solves the issue! If you then use another plugin such as frontmatter links, it's perfect!)

**Comment by mdelobelle** [comment]
released in 0.4.0
