### ISSUE TITLE
Not able to see linked fields

### ISSUE THREAD

**Issue by kmaustral** [mdelobelle/metadatamenu#144]
I have linked a fileClass to a note, but it doesn't reveal the linked fields. 

This is the video: https://www.loom.com/share/e51cd93ccaf94b6f8b15495781b41910

**Comment by mdelobelle** [comment]
Hi thanks for the video
since you haven't defined any type and options for your Person fileClass' fields, it's considered empty and therefore fall-back to the settings-defined fields.

To add a proper field definition in a fileClass you can:
- right click on the fileClass tabheader > manage fields > add new field
- from the fileClass menu, command palette > Metadata Menu: insert a new fileClass attribute.
- or add a fileClass field from the note fields "+" button that you have clicked at the end of your demo and fill the settings

**Comment by kmaustral** [comment]
Thanks. I had assumed from this image that syntax wasn't necessary for text input fields:

music.md
=========
genre
difficulty
masterization
artist
tone
tab available

But I've added `:: {"type":"Input","options":{}}` to each and it works fine now. 

Much appreciated.

**Comment by mdelobelle** [comment]
oh i see,
this was a legacy way of hand-writing fileclasses
i'll change the documentation accordingly
