### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by arminta7** [mdelobelle/metadatamenu#145]
Obsidian is unusable for me with the plugin enabled. Every action takes about 5 seconds to resolve. I do have a healthy sized vault and a lot of metadata and fileClasses. Happy to provide any other info!

**Comment by mdelobelle** [comment]
Ok let's try to isolate the issue:
- Did you map tags with fileclasses? if yes, can you set mapWithTag to "false" in your fileClass definition and see if it  improves the performance
- Did you set multiple fileclasses/supercharged tags in your notes, if yes, can you revert to single. fileclass definition per note and see if it improves the definition?

- Is even typing text slow, or only Metadata Menu commands?

**Comment by mdelobelle** [comment]
Do you use "lookup fields"?
(they also require many queries to check for changes)

**Comment by arminta7** [comment]
- I have 97 fileClasses, all are mapped to tags. I can set them all back, but it will take work lol. 
- I don't usually use more than one tag, but I'm sure a few files have more than one. 
- Everything is slow. Clocking anywhere in the interface. Typing. Opening anything. Even trying to reload Obsidian. 
- I use quite a few lookup fields.

**Comment by mdelobelle** [comment]
ok let's start first with tags.
If you use vscode or any other code/text editor with search and replace, try to bulk-replace "mapWithTag: true" by "mapWithTag: false"

**Comment by arminta7** [comment]
Ok I removed the map with tag and it is much more responsive. I do have thousands of files tagged.

**Comment by mdelobelle** [comment]
ok I have to admit I've not been very cautious about performance with may tag mapping algorithm 😅
on my side, tested with 5000k+ files and 40 fileclasses, each changed was resolved in 90ms which is acceptable.

Anyway, I've an idea how to better leverage all the indexing done by dataview and not iterate all over the vault again.
I'll publish a release in a couple of hours

**Comment by mdelobelle** [comment]
could you try this version?
https://gist.github.com/mdelobelle/2b146b03b4efb21249d6b6132a1e8235

i'm not familiar with beta versions in github so to make it quick-and-dirty:

1. backup the main.js file in .obsidian/plugins/metadatamenu somewhere (so that you can revert without having to uninstall/install the plugin, your settings would be lost) - in case you loose it, you still can recover it from the release assets here https://github.com/mdelobelle/metadatamenu/releases/tag/0.3.2

2. replace the main.js file in .obsidian/plugins/metadatamenu by the one in attachement

3. go to obsidian settings and disable/enable the Metadata Menu plugin

4. start testing: 
with no tag mapped with fileClass, open the console and look for logs like
start index ....
end index ... in <###>ms

<###>ms is the time needed by metadata menu to make the indexing : what does that give you?

start with one fileClass mapped with tag and see if performance is ok (indexing time should increase so much)
increase by 2 more and test, 5 more and test, 10 more and test...

Sorry to bother you with that. I think that I never had a chance to have such a heavy user of the plugin to test the performance 😉

**Comment by arminta7** [comment]
Here it is on first load with no tags mapped

<img width="718" alt="Screenshot 2022-10-28 at 11 32 27" src="https://user-images.githubusercontent.com/7927356/198676165-396e008d-b52b-4159-98b7-455c65d89a15.png">

**Comment by arminta7** [comment]
1 tag

<img width="686" alt="Screenshot 2022-10-28 at 11 33 38" src="https://user-images.githubusercontent.com/7927356/198676432-e70969a2-69e6-4c18-870e-2087a5934cb8.png">

**Comment by arminta7** [comment]
With 3 tags there are too many lines to screenshot, but this is the beginning. 

<img width="690" alt="Screenshot 2022-10-28 at 11 35 53" src="https://user-images.githubusercontent.com/7927356/198676900-6d3b1be2-32c5-488e-8ca2-51dd5d82159f.png">

**Comment by arminta7** [comment]
The console is still going and typing lag is making it difficult for me to edit the frontmatter of other fileClasses. The last tag I mapped is used 510 times.

**Comment by mdelobelle** [comment]
ok thanks a lot. givé the fact that the reindexing increases exponentially each time you add a tag may suggest that the plugin is re-writing lookup fields a lot

I head into this direction. I'll keep u posted

**Comment by mdelobelle** [comment]
made several improvements to indexing, 
introduced the capability to not-auto-update some lookup fields that consume to much dataview queries

This will be shipped in the next version

**Comment by mdelobelle** [comment]
I'll close this one. don't hesitate to open another one if you encounter performance issues in some specific use cases
