### ISSUE TITLE
MultiFile fields with dataview quering language DQL support

### ISSUE THREAD

**Issue by FriedrichStein** [mdelobelle/metadatamenu#149]
Having fields lists based on dataview queries is such a neat feature! 
But since it uses dataviewjs, it's hard (or impossible) to use for people with no coding experience (And I happen to be one of them ;) )
In my case, I had a certain query I wanted to accomplish and it turned out to be not feasable, even with support from the discord community.
Opening up this feature to the way more accesible DQL, would empower a lot of users I think. 

Thank you for developing, its an amazing plug-in!

**Comment by mdelobelle** [comment]
Hi thank you for your feedback, this is much appreciated.
 
This would indeed be a nice feature indeed, and I took the time to look into how I could implement that. 

Unfortunately, even though dataview provides function to execute DQL instructions, it is currently provided in a way (asynchronous method) that is not compatible with metadata menu (mainly because context and right click menu are build synchronously by Obsidian itself).

I guess that trying to make this feature synchronous would be a lot of work on Dataview side, and adapting Metadata Menu to handle asynchronous method to get values for MultiFile fields (or FileFields, Select, MultiSelect) would lead into significant rework and regressions for users (some features wouldn't be accessible through the menus anymore)

I'll try to find decent workaround for those regressions but I'm not sure to be able to achieve that.
