### ISSUE TITLE
Adding YAML field to note without frontmatter has incorrect fieldname

### ISSUE THREAD

**Issue by Spiderbrigade** [mdelobelle/metadatamenu#164]
I'm using the API to add a series of fields to a note via Templater javascript. This works as expected _unless_ the note initially has no frontmatter. In that case the frontmatter is added, but the first field is added as `fieldName` instead of the field I pass. The value I pass is correctly set to that field. Subsequent field additions work correctly (since the frontmatter is there).

For reference I'm calling
```
insertValues(file,field,value,-2,true,false)
```
It's possible this is NOT the best practice to do what I'm trying to do (add a field that doesn't exist to frontmatter).

As a side note it would also be useful to have a function in the API which updates a field if it exists and adds it if it doesn't. I have written a helper that does this by checking if the field exists via getValues() length and then calling either replaceValues() or insertValues(), but this seems inelegant.

**Comment by mdelobelle** [comment]
good catch, there was an issue. it will be fixed in the next version.

About your second point, I think that your approach is the best. 
When you replace values, you don't care where the field is in the note, the plugin searches it for you
When you insert you have to define the location
So if you want to combine the two, if means that if you want to insert a field somewhere but that field already exists elsewhere in the note, it is this instance that will be updated and you won't get the field inserted where you wanted to.

**Comment by mdelobelle** [comment]
fixed in 0.3.6
