### ISSUE TITLE
Can't migrate configuration from SuperCharged Links

### ISSUE THREAD

**Issue by MMoMM-org** [mdelobelle/metadatamenu#166]
I can't click on the checkmark when I want to migrate the SuperCharged Links configuration.
![2022-11-07 16-24-35 - Plugin - Privat - Obsidian v1 0 0 ](https://user-images.githubusercontent.com/115642933/200348072-1f498aa9-79d6-49fb-b39f-cac2cfbceaf9.png)

**Comment by mdelobelle** [comment]
Hi, do you have Supercharged Links enabled? 
If "yes", do you see any error message in the console when clicking on the button?

This feature has been introduced 5 months ago when I've first launched the plugin. The data model has evolved a lot since then, I'm not sure that the migration will work without errors: you should backup your .obsidian/plugins/metadatamenu/data.json file first before applying this migration

**Comment by MMoMM-org** [comment]
yes, but I didn't really use it up to today.
`
plugin:metadata-menu:10553 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at eval (plugin:metadata-menu:10553:31)
    at HTMLButtonElement.<anonymous> (app.js:1:1114448)
`

**Comment by mdelobelle** [comment]
could you paste the content of your .obsidian/plugins/supercharged-links-obsidian/data.json here?

**Comment by MMoMM-org** [comment]
here you go https://gist.github.com/MMoMM-org/b156279901f31eef01f6c54b24e2b9a7

**Comment by mdelobelle** [comment]
thanks. You don't have any preset fields in supercharged links. So migrating is not necessary in your case. I'll create an exception in a future release

**Comment by MMoMM-org** [comment]
thanks
