### ISSUE TITLE
Bring back tags as an array please

### ISSUE THREAD

**Issue by willasm** [mdelobelle/metadatamenu#242]
I do prefer my tags in frontmatter as an array. This was changed after v0.3.10
Please bring this back as an option. With the current version if I change any frontmatter tag value and use the suggester, it converts my tags from an array to the list. I know a lost of people prefer the list method, but the array method is perfectly valid and I prefer it that way.

**Comment by icebruce** [comment]
I think I stumbled on this as well. Just realized my tags are being formatted automatically into a list and was scratching my head as to why, had to do some debugging to figure out it was due to this add-on.

I would also like this to either revert back or provide an option. Right now it is a bit wonky, also a bit redundant when using the linter plugin.

Thanks you!

**Comment by mdelobelle** [comment]
Hi, I totally get your point. 
This is a design pattern that has been introduced in 1.1.9 for all plugins modifying the frontmatter. We've discussed that with the Obsidian team, and there is currently no plan to provide a "display as an array" formating option for the frontmatter section.

The team will eventually work on some UI improvements to display the frontmatter section in a more fancy way, but I'm afraid I have no precise information about that so far.

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by willasm** [comment]
Thank you, works great! I had gone back to v3 to keep my tags the way I use them but now I can enjoy all the new features you have added. 👍
