### ISSUE TITLE
[FR] Support the list form of tags and aliases

### ISSUE THREAD

**Issue by ku-zhen** [mdelobelle/metadatamenu#258]
Hello，can you support the list form of tags and aliases？thanks

![image](https://user-images.githubusercontent.com/61906420/213165067-416ad25c-0242-4753-9f26-3d1ede914f29.png)

**Comment by mdelobelle** [comment]
Hi you can test it in 0.4.11

**Comment by wuzhen97** [comment]
> Hi you can test it in 0.4.11

Hello，I have tested it, but it doesn't seem to work properly. The recorded video demo is as follows. Is it my improper operation? thanks

https://user-images.githubusercontent.com/61906420/213840591-e6df2fb9-5dae-4d10-8ed2-4b8db92045c6.mp4

**Comment by mdelobelle** [comment]
You're attachment is an audio file

**Comment by wuzhen97** [comment]
> Your attachment is an audio file

Sorry，I uploaded it again，and the truth is that the list will become the form like “tags: A, B , C” , not is an indented list, thanks

There is the video with .mp4 format, and if you cant see it again, it may be caused by the sever link: 

https://user-images.githubusercontent.com/61906420/213901762-3b450771-2968-4a59-930a-31a94e2c765a.mp4

The screenshot：


![image](https://user-images.githubusercontent.com/61906420/213901901-70c74478-9085-4562-afa9-7cdece48ae9c.png)

![image](https://user-images.githubusercontent.com/61906420/213901903-5e678629-6942-4d29-a9e7-8939a69f1c27.png)

![image](https://user-images.githubusercontent.com/61906420/213901905-b9e884b8-5f83-4616-b95a-8aa250c09800.png)

**Comment by wuzhen97** [comment]
Hello，I found that only works for the field type something like “... from a list”, but as for "Accept any vaule", it doesnt work.
I think most of  the persons need any vaule for tags and aliases to input，thanks~

**Comment by mdelobelle** [comment]
core tags and aliases will have their own UI for value modification in the next version of obsidian. I'd rather not conflict with this two specific properties in the plugin
