### ISSUE TITLE
Avoid applying class Files to a specific folder (e.g. Templater)

### ISSUE THREAD

**Issue by OXiOSDev** [mdelobelle/metadatamenu#392]
First of all, a huge thanks for this incredible plugin !!!
Using the Templater plugin, i add a tag in the template file to automatically apply a class file in the file generated by the template.
If possible, I would like that the class file was not apply to the templater file itself to avoid to select any value for a field into the template itself (that will be apply to all futur files generated by this template).
Is it possible to add a option into the settings to select folder in which the class file was not apply ?
Or is it possible to add some code into the markdown file of the file class ?
Once again, this plugin is amazing !!!

**Comment by biscotty666** [comment]
There's a plugin called Quick Add which allows you to define macros which can be applied by default to new notes. I've seen it in action but haven't used it myself. You could potentially create a macro which adds the fileClass to the frontmatter rather than putting that part in your template. https://quickadd.obsidian.guide/docs/Choices/MacroChoice

**Comment by OXiOSDev** [comment]
Thanks a lot for your response !
I will try it.

**Comment by mdelobelle** [comment]
I'll add a dedicated setting for that in the next version

**Comment by OXiOSDev** [comment]
Thank you so much for your amazing work !
