### ISSUE TITLE
Performance issue when a MDM tab is open

### ISSUE THREAD

**Issue by koenbunders** [mdelobelle/metadatamenu#465]
When I have no MDM tab (Table view | Fileclass fields | Fileclass settings) open, performance in Obsidian is great. As soon as I have one MDM tab (Table view | Fileclass fields | Fileclass settings) open, the performance becomes terrible. Editor hangs and can't keep up with my typing.

Version 0.6.5 (not sure if this was also happening in earlier version)

**Comment by mdelobelle** [comment]
Hi. I can be due to the building of the table.
Each time there's a modification in a file, dataview trigger a refresh of their queries, and therefore this triggers a refresh of the table that can consume a lot of CPU due to the numerous cells and buttons...
One thing you can try is to limit the number of rows per page. Start small (10 rows or so) and see if it improves the performance
This limit can be set globally in the plugin settings or per fileClass (if you have only some specific fileClass that has tons of fields and many matched files)

**Comment by koenbunders** [comment]
Thanks, that helps a great deal.

> Each time there's a modification in a file, dataview trigger a refresh of their queries, and therefore this triggers a refresh of the table that can consume a lot of CPU due to the numerous cells and buttons...

Would it possible to only trigger the refresh of dataview queries when a tab or window is in front?

**Comment by eicnix** [comment]
I also found that the typing performance is significantly worse when mapping a folder to a fileclass instead of manually adding the fileclass onto every file.

**Comment by mdelobelle** [comment]
> Thanks, that helps a great deal.
> 
> > Each time there's a modification in a file, dataview trigger a refresh of their queries, and therefore this triggers a refresh of the table that can consume a lot of CPU due to the numerous cells and buttons...
> 
> Would it possible to only trigger the refresh of dataview queries when a tab or window is in front?

This should now be the case since 0.6.11.
I'm closing this issue. Don't hesitate to reopen one if you experience slowness in other situations
