### ISSUE TITLE
FR: add text/markdown template to fileClass for full templating functionality

### ISSUE THREAD

**Issue by Rhydderch** [mdelobelle/metadatamenu#541]
As I use metadataMenu as a way to manage templates, I was wondering whether it would be possible to also include markdown into the fileClass.

## Current set up and workflow
For now, metadataMenu only manages the properties of a file and gives the option to update properties/add missing properties. This is great to keep consistent properties across the same type of note. 

However, for the content of the note, I must rely on a markdown template and on the template plugin of obsidian.

So I have currently two templates for each file type

- **a fileClass**: templates properties
- **a markdown file**: contains a template for the body of the note and perhaps some scripts for the templater plugin

## Ideal workflow ✨ (it would be really amazing)
Allow people to add markdown to the fileClass and turn metadataMenu in **the** templating solution.

v1: allow users to add markdown that will be added once the fileClass is assigned to a file or on note creation (with no possibility of updates of the markdown; I guess this could be straightforward to implement?)

v2: use headers as structuring blocks and let users update the structure of notes based on the markdown template (e.g. add missing headers, but do not remove old headers)

<details><summary><b>Example image of what it would look like</b></summary>
<p>
<img width="610" alt="Screenshot 2024-01-16 at 11 07 21" src="https://github.com/mdelobelle/metadatamenu/assets/3197629/303d9640-d009-4232-8bee-fcaf2e7c5da0">

</p>

</details> 

What do you think? :)

**Comment by mdelobelle** [comment]
Hi I get your idea. and this is also a common situation that I've came across several times.
Since it's functionally speaking somewhat different from the purpose of metadata menu, I keep it open but not as a top priority. I'm currently focused on multi-files property editing (progressing slowly 😅) and then consider this idea

**Comment by mAAdhaTTah** [comment]
I would love this as well. One thing to flag in my usage of QuickAdd is file naming. I have a "person" type which I've configured QuickAdd to ask for First & Last name as separate fields, which get combined into the filename. While I would love to have the templates & fileClass feature combined into one plugin, there are definitely a lot of corner-y cases & features to resolve/include here.

**Comment by mdelobelle** [comment]
Hi, in order to keep things as simple as possible, I won't include this feature in the plugin. This really is the realm of templater and both plugin are running quite well together. In combination with Quickadd, you could definitely automate your workflow. 
There's a great demo of it on youtube by Dany Hatcher https://youtu.be/EBcZScQcDKg?si=F3UB3kavt-l7xE3c&t=1481
