### ISSUE TITLE
Date type useage in fileclass

### ISSUE THREAD

**Issue by balola** [mdelobelle/metadatamenu#62]
Hi,
I tried to use date type in fileclass, but throwed an error.
Where was I wrong?
Füles

Fileclass md
![image](https://user-images.githubusercontent.com/24825268/185626038-0b3d5c50-5a4a-4858-a7d5-8bdbc02c600d.png)

Dataviewjs error
![image](https://user-images.githubusercontent.com/24825268/185626143-9278a059-a793-4186-be04-29decbd19837.png)

Dataviewjs code
![image](https://user-images.githubusercontent.com/24825268/185626226-c2aed8ac-e4f8-4041-ab4b-f56270123c3e.png)

Doc with field
![image](https://user-images.githubusercontent.com/24825268/185626598-70c33e11-44d8-42b4-85a9-3c4511a039ee.png)

**Comment by balola** [comment]
Sorry, the fileclass in doc is "Kanban".

**Comment by mdelobelle** [comment]
you'll have to define options for your Date field (see readme for full details) with 3 attributes:
- dateFormat
- defaultInsertAsLink
- linkPath


example
`Bejelent:: {"type": "Date", "options":{"dateFormat": "YYYY-MM-DD ddd", "defaultInsertAsLink": false, "linkPath": ""}}`

I'll fix in the next release so that the error message more explicit

**Comment by balola** [comment]
Thanks, that is great, working.
