### ISSUE TITLE
Icon Not Displaying

### ISSUE THREAD

**Issue by mardybardy** [mdelobelle/metadatamenu#669]
I have the following file class:
---
mapWithTag: true
icon: mic-vocal
---

which should display [this icon](https://lucide.dev/icons/mic-vocal) but it's not displaying anything. Other icons appear to work fine.

I'm using a Samsung Galaxy Fold 5, One UI 6.1, Obsidian 1.5.12.

**Comment by jmonroynieto** [comment]
I had the same problem recently. Does this fileclass have any fields defined? If that is the case, can you tell us if you have a global class set and what happens when you unset it?

I have a problem where fileclasses without fields are not rendered correctly. curretly my only workaround was to take it away. See #666

**Comment by laurentbonet** [comment]
Same problem icon name with a - does not work:
user -> OK
user-round -> KO

I'm on Mac OS 14.4.1, Obsidian 1.6, no theme, made a test with a vault with only dataview and metadata plugin installed

Conrats for the great job done with that plugin

**Comment by mdelobelle** [comment]
@laurentbonet absolutely, the icon set in obsidian is a subset from lucid. Obsidian team is completing the set every few new releases as far as I can tell
