### ISSUE TITLE
different colors when using select in dataview

### ISSUE THREAD

**Issue by imeed166** [mdelobelle/metadatamenu#71]
When using select properties in dataview it would be nice to auto-generate different colors for different options to differentiate between them in the table

This is when using the option `options: {alwaysOn: true}`

**Comment by imeed166** [comment]
<img width="109" alt="select colors" src="https://user-images.githubusercontent.com/38974541/186875542-daf0e7d3-352e-4db0-b205-d8eb0f16fe58.png">

**Comment by mdelobelle** [comment]
This is not feasible at the moment since this is a standard select field that doesn't support styling with css. https://stackoverflow.com/questions/7208786/how-to-style-the-option-of-an-html-select-element

sorry about that, I won't be able to do this without including a complete custom dropdown component, that would require a significant amount of work
