### ISSUE TITLE
Autocompletion is not triggered right away

### ISSUE THREAD

**Issue by icebruce** [mdelobelle/metadatamenu#8]
**Steps to reproduce**
1. Define list of values in the settings
2. In a new note add new fields in YAML

**Actual results**
1. Autocompletion is not triggered after ":", instead you need to hit enter or backspace for the list to be shown

https://user-images.githubusercontent.com/66655064/179426102-f6e1757b-87b7-4d59-b469-2c6ffd66ce9b.mp4

SYSTEM INFO:
	Obsidian version: v0.15.6
	Installer version: v0.14.6
	Operating system: Windows 10 Pro 10.0.19043
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal

**Comment by mdelobelle** [comment]
Hi, thanks for pointing this out.
this is a limitation due to the time needed by obsidian to refresh the cache of the file.
When you type a field in YAML section, this section is considered unproperly formatted by obsidian (and therefore non existing in cache) until you have typed `field:` AND that the cache has been refreshed by obsidian.
Another workaround is to wait a second or 2 after typing `field:` so that when you type enter afterwards, autocomplete modal shows up

I'll try other way to improve that and keep you posted
