### ISSUE TITLE
MM reads Dataview field as nonsense

### ISSUE THREAD

**Issue by brimwats** [mdelobelle/metadatamenu#93]
Hello!

lovely job with this plugin. I was testing it out and noticed that MM was reading this field wrong. any ideas?

![image](https://user-images.githubusercontent.com/73113656/188346047-21a1de13-a02f-4b58-8146-28d35a9e97d3.png)

**Comment by mdelobelle** [comment]
Hi thank you for your feedback. Good catch on this one: dataview is automatically converting it in a duration: 1930s meaning 1930 seconds for it, which corresponds to 31 minutes and 50 seconds. When stringifying 1910 seconds in "Pacific Time" that gives us this result.
I'll find a way to fix that n the next release

**Comment by mdelobelle** [comment]
I've opened an issue for Dataview team a while ago.
Metadata Menu is leveraging dataview index (for performance purposes). This index transforms automatically the fields' values
In order to display properly the value that I get from dataview, I've asked them to add a "row value" attribute to their index.
I'll keep you posted when it's done

**Comment by mdelobelle** [comment]
will be solved in next version (at last!!!)
I've reduced the dependency on dataview, avoiding values being interpreted unexpectidly as durations

**Comment by mdelobelle** [comment]
At last I can close this issue 😅 this is the one that made me rewrite the whole plugin …. and that was a very good thing!
